### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by quasipedia** [fxdgear/atom-python-debugger#15]
[Enter steps to reproduce below:]

1. On a fresh installation, install the module as below
2. Create and save a small `myfile.py`
3. Press F7 on one of the lines of the `main()` function

**Atom Version**: 0.209.0
**System**: "Fedora release
**Thrown From**: [atom-python-debugger](https://github.com/fxdgear/atom-python-debugger) package, v0.3.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/mac/.atom/packages/atom-python-debugger/lib/python-debugger.js:34

TypeError: undefined is not a function
  at Object.module.exports.insert (/home/mac/.atom/packages/atom-python-debugger/lib/python-debugger.js:34:12)
  at atom-workspace.<anonymous> (/home/mac/.atom/packages/atom-python-debugger/lib/python-debugger.js:10:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:09.4.0 application:open-file (atom-text-editor.editor.is-focused)
 10x -1:04.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:01.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:01.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:01.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:59 core:save (atom-text-editor.editor.is-focused)
     -0:57.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:49.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:48.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:48.7.0 application:run-all-specs (atom-text-editor.editor)
     -0:04.9.0 core:cut (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.6.0 python-debugger:insert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-python-debugger, v0.3.3
autocomplete-plus-python-jedi, v0.3.6
linter, v0.12.7
linter-flake8, v1.4.2
linter-pep257, v0.2.1
linter-pyflakes, v0.0.5

# Dev
No dev packages
```

**Comment by fxdgear** [comment]
Thank you. 

Will look into it asap. 

(I'm thinking about switching to atom full time now)
