### ISSUE TITLE
Fail on files with first line commented.

### ISSUE THREAD

**Issue by artyom-smushkov** [fxdgear/atom-python-debugger#19]
[Enter steps to reproduce below:]
1. Open some python file.
2. Comment the first line.
3. Press F7 on any of the lines.

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [atom-python-debugger](https://github.com/fxdgear/atom-python-debugger) package, v0.3.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/templarrr/.atom/packages/atom-python-debugger/lib/python-debugger.js:41

TypeError: undefined is not a function
    at Object.module.exports.insert (/home/templarrr/.atom/packages/atom-python-debugger/lib/python-debugger.js:41:14)
    at atom-workspace.<anonymous> (/home/templarrr/.atom/packages/atom-python-debugger/lib/python-debugger.js:10:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:241:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:180:20)
```

### Commands

```
  4x -2:23.7.0 core:undo (atom-text-editor.editor.is-focused)
     -2:21.9.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -1:10.7.0 python-debugger:insert (atom-text-editor.editor.is-focused)
     -1:02.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:01.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:56.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:52.8.0 python-debugger:remove (atom-text-editor.editor.is-focused)
 31x -0:50.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:42.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:37.3.0 core:delete (atom-text-editor.editor.is-focused)
     -0:35.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.3.0 python-debugger:insert (atom-text-editor.editor.is-focused)
 42x -0:20.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.2.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:01.7.0 python-debugger:insert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-python-debugger, v0.3.4
autocomplete-plus-python-jedi, v0.3.6
django-templates, v0.5.0
linter, v1.2.4
linter-flake8, v1.5.0
python-isort, v0.0.7
script, v2.26.3

# Dev
No dev packages
```

**Comment by artyom-smushkov** [comment]
Just noticed this is already fixed in repo.
