### ISSUE TITLE
if add notes '#!/usr/bin/env python' at the top of the file,  it would throw an error 'Uncaught TypeError: undefined is not a function'

### ISSUE THREAD

**Issue by ethe** [fxdgear/atom-python-debugger#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.3
**Thrown From**: [atom-python-debugger](https://github.com/fxdgear/atom-python-debugger) package, v0.3.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/go/.atom/packages/atom-python-debugger/lib/python-debugger.js:41

TypeError: undefined is not a function
  at Object.module.exports.insert (/home/go/.atom/packages/atom-python-debugger/lib/python-debugger.js:41:14)
  at atom-workspace.<anonymous> (/home/go/.atom/packages/atom-python-debugger/lib/python-debugger.js:10:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -3:40.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-gruvbox.theme-atom-material-ui)
     -1:52.6.0 command-palette:toggle (atom-pane.pane.active)
     -1:50.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:50.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:42.8.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:05.7.0 python-debugger:insert (atom-text-editor.editor.is-focused)
     -0:57.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:55 python-debugger:insert (atom-text-editor.editor.is-focused)
  3x -0:53.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:43 python-debugger:insert (atom-text-editor.editor.is-focused)
  7x -0:40.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:31.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.5.0 python-debugger:insert (atom-text-editor.editor.is-focused)
     -0:23.5.0 grammar-selector:show (atom-text-editor.editor)
  5x -0:20 core:undo (atom-text-editor.editor.is-focused)
     -0:00.5.0 python-debugger:insert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "gruvbox"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      "*.pyc",
      ".idea"
    ],
    "disabledPackages": [
      "tree-view-filter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.0
atom-python-debugger, v0.3.4
autocomplete-python, v0.5.3
file-icons, v1.6.7
gruvbox, v1.0.5
linter-pep8, v1.0.1
minimap, v4.13.1
simplified-chinese-menu, v3.2.4
tool-bar, v0.1.8
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by ethe** [comment]
i tried recent now and found that whatever comment i added at the file head, debugger would throw this error

**Comment by ethe** [comment]
![2015-08-23 17 51 17](https://cloud.githubusercontent.com/assets/12211036/9427753/9ea6edc8-49bf-11e5-8042-015df618a9db.png)

**Comment by wmayner** [comment]
:+1:

**Comment by ethe** [comment]
it fixed, move `line 41: editor.moveCursorDown();`  to `editor.moveCursorDown();`. atom doesnt have that method.
